### PR TITLE
fix file get thing

### LINKED ISSUE #225: GET request supplied with --request sent as POST
Looks like it's due to these lines:
https://github.com/ffuf/ffuf/blob/master/main.go#L456-L460

as the data is always set when parsing the request file:
https://github.com/ffuf/ffuf/blob/master/main.go#L537

Should be a trivial fix, will PR in a few minutes

### PR DESCRIPTION
**Pull request by C-Sto**
Should resolve #225 

Very minimal changes, so I doubt it will introduce any issues, but for the record I didn't thoroughly verify it.

Not sure what you'd like to do with versioning etc :)

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -453,7 +453,7 @@ func prepareConfig(parseOpts *cliOptions, conf *ffuf.Config) error {
 	}
 
 	// Handle copy as curl situation where POST method is implied by --data flag. If method is set to anything but GET, NOOP
-	if conf.Method == "GET" {
+	if conf.Method == "GET" && len(parseOpts.request) == 0 {
```
Comment (joohoi) [inline main.go:456]: Can you add comment here to point out why this condition exists. It'll help figuring out what's going on in the future :)
